export default {
  /*
   * OPEN SCENE
   */
  // ユーザの初期登録
  OPENED_INITIALIZE: 'OPENED_INITIALIZE',
  OPENED_SELECT_LANGUAGE: 'OPENED_SELECT_LANGUAGE',
  OPENED_INPUT_USER_NAME: 'OPENED_INPUT_USER_NAME',
  OPENED_SIGN_UP: 'OPENED_SIGN_UP',

  // 初期登録完了
  CREATED_USER: 'CREATED_USER',

  // 日記投稿
  CREATED_DIARY: 'CREATED_DIARY',
};
