module.exports = {
  BagPoints: require ('./bagPoints.png'),
  BlankProfile: require ('./blankProfile.png'),
  FLogo: require ('./fLogo.png'),
  Email: require ('./email.png'),
  Loading: require ('./loading.gif'),
  Zebbu: require ('./zebbu.png'),
  Logo: require ('./logo.png'),
  LogoVercitacl: require ('./logo_vertical.png'),
  Star: require ('./star.png'),
  Points: require ('./points.png'),
  GetPoints: require ('./getPoints.png'),
  Pen: require ('./pen.png'),
  People: require ('./people.png'),
};
