module.exports = {
  BagPoints: require('./bagPoints.png'),
  FlashLeft: require('./flash_left.png'),
  FlashRight: require('./flash_right.png'),
  GetPoints: require('./getPoints.png'),
  Loading: require('./loading.gif'),
  LogoVercitacl: require('./logo_vertical.png'),
  Note: require('./note.png'),
  Pen: require('./pen.png'),
  People: require('./people.png'),
  Points: require('./points.png'),
  SavePoints: require('./savePoints.png'),
  Star: require('./star.png'),
  Zebbu: require('./zebbu.png'),
  Zenny: require('./zenny.png'),
};
