export enum Types {
  // User
  SET_USER = 'SET_USER',
  SET_POINTS = 'SET_POINTS',
  // Profile
  SET_PROFILE = 'SET_PROFILE',
  // DiaryList
  SET_DIARIES = 'SET_DIARIES',
  SET_DIARY_TOTAL_NUM = 'SET_DIARY_TOTAL_NUM',
  ADD_DIARY = 'ADD_DIARY',
  DELETE_DIARY = 'DELETE_DIARY',
  // DraftDiaryList
  SET_DRAFT_DIARIES = 'SET_DRAFT_DIARIES',
  SET_DRAFT_DIARY_TOTAL_NUM = 'SET_DRAFT_DIARY_TOTAL_NUM',
  ADD_DRAFT_DIARY = 'ADD_DRAFT_DIARY',
}
