export enum Types {
  // LocalStatus
  SET_LOCAL_STATUS = 'SET_LOCAL_STATUS',
  SET_UNREAD_CORRECTION_NUM = 'SET_UNREAD_CORRECTION_NUM',
  SET_MY_DIARY_LIST_VIEW = 'SET_MY_DIARY_LIST_VIEW',
  RESTORE_UID = 'RESTORE_UID',
  SIGN_IN = 'SIGN_IN',
  SIGN_OUT = 'SIGN_OUT',
  // User
  SET_USER = 'SET_USER',
  // Profile
  SET_PROFILE = 'SET_PROFILE',
  // DiaryList
  SET_DIARIES = 'SET_DIARIES',
  ADD_DIARIES = 'ADD_DIARIES',
  SET_FETCH_INFO = 'SET_FETCH_INFO',
  SET_DIARY_TOTAL_NUM = 'SET_DIARY_TOTAL_NUM',
  ADD_DIARY = 'ADD_DIARY',
  EDIT_DIARY = 'EDIT_DIARY',
  DELETE_DIARY = 'DELETE_DIARY',
  // TeachDiaryList
  SET_TEACH_DIARIES = 'SET_TEACH_DIARIES',
  EDIT_TEACH_DIARY = 'EDIT_TEACH_DIARY',
}
