module.exports = {
  App: require('./app.png'),
  Appstore: require('./appstore.png'),
  CommentEn: require('./comment_en.png'),
  CommentJa: require('./comment_ja.png'),
  CorrectEn: require('./correct_en.png'),
  CorrectJa: require('./correct_ja.png'),
  EntryEn: require('./entry_en.png'),
  EntryJa: require('./entry_ja.png'),
  Giar: require('./girl_01.png'),
  GiarEn: require('./girl_en.png'),
  GiarJa: require('./girl_ja.png'),
  GiarKo: require('./girl_ko.png'),
  GiarZh: require('./girl_zh.png'),
  GooglePlayBadge: require('./google-play-badge.png'),
  Icon: require('./icon.png'),
  IconSmall: require('./icon_small.png'),
  Note: require('./note.png'),
  Pen: require('./pen.png'),
  PointGet: require('./point_get.png'),
  Sample: require('./sample.png'),
  SummaryEn: require('./summary_en.png'),
  SummaryJa: require('./summary_ja.png'),
  Zebra: require('./zebra.png'),
  Zenny: require('./zenny.png'),
};
