module.exports = {
  App: require('./app.png'),
  Appstore: require('./appstore.png'),
  CommentEn: require('./comment_en.png'),
  CommentJp: require('./comment_jp.png'),
  CorrectJp: require('./correct_jp.png'),
  EntryEn: require('./entry_en.png'),
  EntryJp: require('./entry_jp.png'),
  Giar: require('./girl_01.png'),
  GiarEn: require('./girl_en.png'),
  GiarJp: require('./girl_jp.png'),
  GiarKo: require('./girl_ko.png'),
  GiarZh: require('./girl_zh.png'),
  GooglePlayBadge: require('./google-play-badge.png'),
  Note: require('./note.png'),
  Pen: require('./pen.png'),
  PointGet: require('./point_get.png'),
  Sample: require('./sample.png'),
  SummaryEn: require('./summary_en.png'),
  SummaryJp: require('./summary_jp.png'),
  Zebra: require('./zebra.png'),
  Zenny: require('./zenny.png'),
  CorrectEn: require('./correct_en.png'),
};
